from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime


class YahooFinancialsInfo(BaseModel):
    address1: Optional[str] = Field(None)
    address2: Optional[str] = Field(None)
    city: Optional[str] = Field(None)
    zip: Optional[str] = Field(None)
    country: Optional[str] = Field(None)
    phone: Optional[str] = Field(None)
    website: Optional[str] = Field(None)
    industry: Optional[str] = Field(None)
    industrykey: Optional[str] = Field(None)
    industrydisp: Optional[str] = Field(None)
    sector: Optional[str] = Field(None)
    sectorkey: Optional[str] = Field(None)
    sectordisp: Optional[str] = Field(None)
    longbusinesssummary: Optional[str] = Field(None)
    fulltimeemployees: Optional[str] = Field(None)
    compensationasofepochdate: Optional[str] = Field(None)
    maxage: Optional[str] = Field(None)
    pricehint: Optional[str] = Field(None)
    previousclose: Optional[str] = Field(None)
    open: Optional[str] = Field(None)
    daylow: Optional[str] = Field(None)
    dayhigh: Optional[str] = Field(None)
    regularmarketpreviousclose: Optional[str] = Field(None)
    regularmarketopen: Optional[str] = Field(None)
    regularmarketdaylow: Optional[str] = Field(None)
    regularmarketdayhigh: Optional[str] = Field(None)
    beta: Optional[str] = Field(None)
    trailingpe: Optional[str] = Field(None)
    forwardpe: Optional[str] = Field(None)
    volume: Optional[str] = Field(None)
    regularmarketvolume: Optional[str] = Field(None)
    averagevolume: Optional[str] = Field(None)
    averagevolume10days: Optional[str] = Field(None)
    averagedailyvolume10day: Optional[str] = Field(None)
    bid: Optional[str] = Field(None)
    ask: Optional[str] = Field(None)
    bidsize: Optional[str] = Field(None)
    asksize: Optional[str] = Field(None)
    marketcap: Optional[str] = Field(None)
    fiftytwoweeklow: Optional[str] = Field(None)
    fiftytwoweekhigh: Optional[str] = Field(None)
    pricetosalestrailing12months: Optional[str] = Field(None)
    fiftydayaverage: Optional[str] = Field(None)
    twohundreddayaverage: Optional[str] = Field(None)
    currency: Optional[str] = Field(None)
    enterprisevalue: Optional[str] = Field(None)
    profitmargins: Optional[str] = Field(None)
    floatshares: Optional[str] = Field(None)
    sharesoutstanding: Optional[str] = Field(None)
    sharesshort: Optional[str] = Field(None)
    sharesshortpriormonth: Optional[str] = Field(None)
    sharesshortpreviousmonthdate: Optional[str] = Field(None)
    dateshortinterest: Optional[str] = Field(None)
    sharespercentsharesout: Optional[str] = Field(None)
    heldpercentinsiders: Optional[str] = Field(None)
    heldpercentinstitutions: Optional[str] = Field(None)
    shortratio: Optional[str] = Field(None)
    shortpercentoffloat: Optional[str] = Field(None)
    impliedsharesoutstanding: Optional[str] = Field(None)
    bookvalue: Optional[str] = Field(None)
    pricetobook: Optional[str] = Field(None)
    lastfiscalyearend: Optional[str] = Field(None)
    nextfiscalyearend: Optional[str] = Field(None)
    mostrecentquarter: Optional[str] = Field(None)
    earningsquarterlygrowth: Optional[str] = Field(None)
    netincometocommon: Optional[str] = Field(None)
    trailingeps: Optional[str] = Field(None)
    forwardeps: Optional[str] = Field(None)
    pegratio: Optional[str] = Field(None)
    enterprisetorevenue: Optional[str] = Field(None)
    enterprisetoebitda: Optional[str] = Field(None)
    fiftytwoweekchange: Optional[str] = Field(None)
    sandp52weekchange: Optional[str] = Field(None)
    exchange: Optional[str] = Field(None)
    quotetype: Optional[str] = Field(None)
    symbol: Optional[str] = Field(None)
    underlyingsymbol: Optional[str] = Field(None)
    shortname: Optional[str] = Field(None)
    longname: Optional[str] = Field(None)
    firsttradedateepochutc: Optional[str] = Field(None)
    timezonefullname: Optional[str] = Field(None)
    timezoneshortname: Optional[str] = Field(None)
    uuid: Optional[str] = Field(None)
    messageboardid: Optional[str] = Field(None)
    gmtoffsetmilliseconds: Optional[str] = Field(None)
    currentprice: Optional[str] = Field(None)
    targethighprice: Optional[str] = Field(None)
    targetlowprice: Optional[str] = Field(None)
    targetmeanprice: Optional[str] = Field(None)
    targetmedianprice: Optional[str] = Field(None)
    recommendationmean: Optional[str] = Field(None)
    recommendationkey: Optional[str] = Field(None)
    numberofanalystopinions: Optional[str] = Field(None)
    totalcash: Optional[str] = Field(None)
    totalcashpershare: Optional[str] = Field(None)
    ebitda: Optional[str] = Field(None)
    totaldebt: Optional[str] = Field(None)
    quickratio: Optional[str] = Field(None)
    currentratio: Optional[str] = Field(None)
    totalrevenue: Optional[str] = Field(None)
    debttoequity: Optional[str] = Field(None)
    revenuepershare: Optional[str] = Field(None)
    returnonassets: Optional[str] = Field(None)
    returnonequity: Optional[str] = Field(None)
    freecashflow: Optional[str] = Field(None)
    operatingcashflow: Optional[str] = Field(None)
    earningsgrowth: Optional[str] = Field(None)
    revenuegrowth: Optional[str] = Field(None)
    grossmargins: Optional[str] = Field(None)
    ebitdamargins: Optional[str] = Field(None)
    operatingmargins: Optional[str] = Field(None)
    financialcurrency: Optional[str] = Field(None)
    trailingpegratio: Optional[str] = Field(None)
    ticker: Optional[str] = Field(None)
    upload_date: Optional[str] = Field(None)
    exdividenddate: Optional[float] = Field(None)
    lastsplitfactor: Optional[str] = Field(None)
    lastsplitdate: Optional[float] = Field(None)
    lastdividendvalue: Optional[float] = Field(None)
    lastdividenddate: Optional[float] = Field(None)
    state: Optional[str] = Field(None)
    auditrisk: Optional[str] = Field(None)
    boardrisk: Optional[str] = Field(None)
    compensationrisk: Optional[str] = Field(None)
    shareholderrightsrisk: Optional[str] = Field(None)
    overallrisk: Optional[str] = Field(None)
    governanceepochdate: Optional[str] = Field(None)
    fax: Optional[str] = Field(None)
    dividendrate: Optional[str] = Field(None)
    dividendyield: Optional[str] = Field(None)
    trailingannualdividendrate: Optional[str] = Field(None)
    trailingannualdividendyield: Optional[str] = Field(None)
    payoutratio: Optional[str] = Field(None)
    fiveyearavgdividendyield: Optional[str] = Field(None)
    totalassets: Optional[str] = Field(None)
    navprice: Optional[str] = Field(None)
    category: Optional[str] = Field(None)
    fundfamily: Optional[str] = Field(None)
    fundinceptiondate: Optional[str] = Field(None)
    legaltype: Optional[str] = Field(None)
    yield_: Optional[str] = Field(None, alias="yield")
    ytdreturn: Optional[str] = Field(None)
    beta3year: Optional[str] = Field(None)
    threeyearaveragereturn: Optional[str] = Field(None)
    fiveyearaveragereturn: Optional[str] = Field(None)


class YahooFinancialsIncomeStatement(BaseModel):
    ticker: Optional[str] = Field(None)
    upload_date: Optional[datetime] = Field(None)
    kpi: Optional[str] = Field(None)
    date: Optional[datetime] = Field(None)
    value: Optional[float] = Field(None)


class YahooFinancialsBalanceSheet(BaseModel):
    ticker: Optional[str] = Field(None)
    upload_date: Optional[datetime] = Field(None)
    kpi: Optional[str] = Field(None)
    date: Optional[datetime] = Field(None)
    value: Optional[float] = Field(None)


class YahooFinancialsCashFlow(BaseModel):
    ticker: Optional[str] = Field(None)
    upload_date: Optional[datetime] = Field(None)
    kpi: Optional[str] = Field(None)
    date: Optional[datetime] = Field(None)
    value: Optional[float] = Field(None)


class YahooFinancialsHistory(BaseModel):
    date: Optional[datetime] = Field(None)
    open: Optional[float] = Field(None)
    high: Optional[float] = Field(None)
    low: Optional[float] = Field(None)
    close: Optional[float] = Field(None)
    volume: Optional[int] = Field(None)
    dividends: Optional[float] = Field(None)
    stock_splits: Optional[float] = Field(None)
    ticker: Optional[str] = Field(None)
    upload_date: Optional[datetime] = Field(None)
