"""Initial Setup

Revision ID: d4b3e5a1ac12
Revises: 
Create Date: 2024-05-05 19:33:09.797076

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "d4b3e5a1ac12"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("telegram_id", sa.Integer(), nullable=False))
    op.add_column(
        "user",
        sa.Column(
            "telegram_username", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "telegram_username")
    op.drop_column("user", "telegram_id")
    # ### end Alembic commands ###
