# CONSTANTS

YAHOO_TRAVEL_TICKERS = [
    "TRIP",
    "LVS",
    "AZUL",
    "NCLH",
    "RCL",
    "JBLU",
    "ITHL.BO",
    "THOMASCOOK.NS",
    "NNAX",
    "IRCTC",
    "HLT",
    "YATRA.BO",
    "LIND",
    "CHH",
    "TUIFF",
    "EZJ.L",
    "DIS",
    "HLO",
    "AMADF",
    "INDIGO.NS",
    "YTRA",
    "AC",
    "ONVC",
    "DESP",
    "TRN",
    "CCHHL.NS",
    "THOMASCOOK.BO",
    "LUV",
    "TOUR",
    "IHG",
    "INDHOTEL.NS",
    "TZOO",
    "GBTG",
    "HTZ",
    "MAORF",
    "LGDDF",
    "HSW",
    "DUFRY",
    "RYAAY",
    "MINT",
    "CCL",
    "MOND",
    "BKNG",
    "MHRIL",
    "LHA.DE",
    "THOMASCOOK",
    "ULCC",
    "HSWLF",
    "SPICEJET.NS",
    "AF.PA",
    "TAJGVK",
    "LMN.SW",
    "LEMONTREE.NS",
    "EDDRF",
    "WEB",
    "NTRP",
    "TRVG",
    "TCOM",
    "THYAO.IS",
    "CAR",
    "TGBHOTELS.NS",
    "DAL",
    "FLT",
    "QAN",
    "MAR",
    "C6L",
    "AAL",
    "ROHLTD",
    "MHSGRMS",
    "AL",
    "EXPE",
    "GINX",
    "WH",
    "TUI1",
    "YATRA.NS",
    "VCSA",
    "ALK",
    "AMADY",
    "EASEMYTRIP.NS",
    "SDRMF",
    "ALGT",
    "OTB",
    "WTICAB",
    "UAL",
    "SAVE",
    "CTD",
    "ABNB",
    "SKYW",
    "TNL",
    "EASEMYTRIP",
    "EASEMYTRIP.BO",
    "SABR",
    "ISPO",
    "ISPOW",
    "MEL",
    "EDR",
    "CDNO",
    "MMYT",
    "TRZBF",
    "HA",
]

YAHOO_FINANCE_STATEMENT_TYPES = [
    # "info", --> not needed
    "income_statement",
    "balance_sheet",
    "cashflow",
    "history",
]


# Earnings Reports LINKS
earnings_reports_links = {
    "bookingholdings": "https://ir.bookingholdings.com/financials/quarterly-results/default.aspx",
    "priceline": "https://www.priceline.com/earnings-reports",
    "tripadvisor": "https://www.tripadvisor.com/earnings-reports",
}
